refactoring and added parallelism
mexikoedi/Anime-New-Season-Checker pull request #3
Opened 2023-01-31 13:12 UTC by neumann-dev

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] I have tested the changes.
- [ ] This is not a duplicate.
- [ ] I have read the README file and the description.
- [ ] I have added a description which explains this pull request.
- [ ] All new and existing tests passed.

## Description

Added parallelism with streams and refactored the code to an more objective-oriented way

2023-01-31 22:24 UTC, mexikoedi requested changes
I noticed some small code style stuff.
See my comments.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		this.tfAnimeHeadline = initTextField(dragPanel,
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		this.tfAnimeSeasonHeadline = initTextField(dragPanel,
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		this.tfAnimeRunHeadline = initTextField(dragPanel,
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		this.tfControls = initTextField(dragPanel,
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		this.tfSeason = initTextField(dragPanel,
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		this.tfAnimeCount = initTextField(dragPanel,
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		this.tfDuration = initTextField(dragPanel,
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		for (Anime anime : this.animeList) {
Add whitespace before for.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +			initTextField(this.dragPanel,
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +			this.tfAnimeSeasonMap.put(anime.getName(),
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +			this.tfAnimeRunMap.put(anime.getName(),
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +	private JTextField initTextField(JPanel dragPanel,
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		if (horizontalAlignment != null)
Add whitespace before if and add whitespace after statement.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +		if (text != null)
Add whitespace before if and add whitespace after statement.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +				JOptionPane.showMessageDialog(null, "Error: " +
Format code here so it is in one line instead of multiple lines.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +			// When seasonElement is null there is only one season
Add whitespace above comment.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +			if (numberOfSeasons.equals(expectedNumberOfSeasons)) {
Add whitespace before if and add whitespace after else statement.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +
Remove one whitespace.

2023-01-31 22:24 UTC, mexikoedi commented on src/ansc/ANSChecker.java
> +			if (website.select("#browse-episodes-year.ipc-simple-select__input").text().contains("See all")) {
Add whitespace before if.

2023-01-31 22:24 UTC, mexikoedi commented on src/model/AnimeListReader.java
> +                if (textLine.lastIndexOf("source:") >= 0) {
Add whitespace before if.

2023-02-13 17:02 UTC, neumann-dev commented
the code style stuff is done

2023-02-13 22:53 UTC, mexikoedi approved these changes
Looks good to me.
I will do one or two changes here and there but in overall good.

2023-02-13 22:56 UTC, merged